# Configuration file for defining desired reservations

# -- Reservation Details --
# Number of People
num_people: 4
# Event Name
event_name: Group Study

# Event Type. Options: STUDY_ROOM or NAP_NOOK
event_type: STUDY_ROOM

# 1st Contact Name
contact_name: Jackson Wheeler

# 1st Contact Phone Number 
contact_phone: 952-737-7547

# 1st Contact Email
contact_email: j1wheele@ucsd.edu

# Description of Event
description: Group Study 
# --- End of Reservation Details ---


# -- Room Preference Order --
# Notes:
  # Use "PC #". Example: "PC 0" for "Price Center Study Room 0"
  # And use "PLB" for "Port of Long Beach"
room_preference_order:
  - PC 0
  - PC 4
  - PC 5
  - PC 6
# --- End of Room Preference Order ---


# -- Reservation Dates & Times --
# Make reservations for multiple weeks by adding more "start_of_week_date" sections
reservation_dates_and_times:

  # Start of Week Date (Sunday) - write the date for the Sunday of the week you want to reserve
  - start_of_week_date: 1/14/2024
    # Days of the week you want to reserve & the start/end times for each day 
    # (Comment out, or delete, any days you don't want to reserve)
    reservations:

      Monday:
        startTime: 11am
        endTime: 3pm

      Tuesday:
        startTime: 11am
        endTime: 3pm

      Wednesday:
        startTime: 11am
        endTime: 3pm
        
      Thursday:
        startTime: 11am
        endTime: 3pm

      Friday:
        startTime: 11am
        endTime: 3pm

  # Start of Week Date (Sunday) - write the date for the Sunday of the week you want to reserve
  - start_of_week_date: 1/14/2024
    # Days of the week you want to reserve & the start/end times for each day 
    # (Comment out, or delete, any days you don't want to reserve)
    reservations:

      Monday:
        startTime: 11am
        endTime: 3pm

      Tuesday:
        startTime: 11am
        endTime: 3pm

      Wednesday:
        startTime: 11am
        endTime: 3pm
        
      Thursday:
        startTime: 11am
        endTime: 3pm

      Friday:
        startTime: 11am
        endTime: 3pm

# --- End of Reservation Dates & Times ---