# Configuration file for defining desired reservations

# -- Reservation Details --
reservation_details:
  # Number of People
  num_people: 4
  # Event Name
  event_name: Group Study

  # Event Type. Options: STUDY_ROOM or NAP_NOOK
  event_type: STUDY_ROOM

  # 1st Contact Name
  contact_name: Jackson Wheeler

  # 1st Contact Phone Number 
  contact_phone: 952-737-7547

  # 1st Contact Email
  contact_email: j1wheele@ucsd.edu

  # Description of Event
  description: Group Study 
# --- End of Reservation Details ---


# -- Room Preference Order --
# Note: write name exactly as it appears on the reservation page
room_preference_order:
  - Price Center Study Room 0
  - Price Center Study Room 4
  - Price Center Study Room 5
  - Price Center Study Room 6
# --- End of Room Preference Order ---


# -- Reservation Dates & Times --
reservation_times:
  - date: 1/23/2024
    startTime: 11am
    endTime: 3pm
  - date: 1/24/2024
    startTime: 11am
    endTime: 3pm
  - date: 1/25/2024
    startTime: 11am
    endTime: 3pm
  - date: 1/28/2024
    startTime: 11am
    endTime: 3pm
  - date: 1/29/2024
    startTime: 11am
    endTime: 3pm
# --- End of Reservation Dates & Times ---